const dectionary = {
    arabic: {
        name: ' الاسم ',
        company: ' الشركة ',
        type: ' النوع ',
        buyingPrice: ' سعر الشراء (القطعة) ',
        sellingPrice: ' سعر المبيع (القطعة) ',
        date: ' التاريخ ',
        id: ' المعرف ',
        customer: ' العميل ',
        productName: ' اسم المنتج ',
        productId: ' رقم المنتج ',
        profit: ' الربح ',
        quantity: ' الكمية ',
        add: ' إضافة ',
        totalSales: ' مجموع المبيعات ',
        soldProductsNumbers: ' عدد المنتجات المباعة ',
        totalProfit: ' الربح الكلي ',
        addToSoldProductList: ' إضافة إلى قائمةالمبيعات ',
        pleaseInsertProductName: ' الرجاء إدخال اسم منتج ',
        customerName: ' اسم العميل ',
        pleaseAddBuyingPrice: ' الرجاء إضافة سعر الشراء ',
        pleaseAddQuentity: ' الرجاء إضافة الكمية ',
        addProduct: ' إضافة المنتج ',
        addProductToWareHouse: ' أضف منتج إلى المخزن ',
        pleaseAddSellingPrice: ' الرجاء إضافةسعر البيع ',
        buyingDate: ' تاريخ الشراء ',
        sell: ' بيع ',
        productCount: ' عدد المنتجات ',
        totalInitialProfit: ' الربح الاولي ',
        totalProductPrice: ' ثمن البضاعة الكلية ',
        wareHouse: ' المخزن ',
        totalSellingPrice: ' سعر المبيع الكلي ',
        totalBuyingPrice: ' سعر الشراء الكلي ',
        notEnoughProductToSell: ' لا يوجد كمية كافية ',
        quantityInWareHouse: ' الكمية في المستودع ',
        wareHouseId: ' مكان المنتج في المستودع ',
        sales: ' المبيعات ',
        products: ' المنتجات ',
        typeId: ' معرف النوع ',
        companyId: ' معرف الشركة ',
        saleId: ' معرف البيعة ',
    },
    english: {
        name: ' name ',
        company: ' company ',
        type: ' type ',
        buyingPrice: ' buying Price ',
        sellingPrice: ' selling Price ',
        date: ' date ',
        id: ' id ',
        customer: ' customer ',
        productName: ' product Name ',
        productId: ' product Id ',
        profit: ' profit ',
        quantity: ' quantity ',
        add: ' add ',
        totalSales: '  total Sales  ',
        soldProductsNumbers: '  sold ProductsNumbers  ',
        totalProfit: ' total Profit ',
        addToSoldProductList: ' add To Sold Product List ',
        pleaseInsertProductName: ' please Insert Product Name ',
        customerName: ' customer Name ',
        pleaseAddBuyingPrice: ' please Add Buying Price ',
        pleaseAddQuentity: ' please Add Quentity ',
        addProduct: ' add Product ',
        addProductToWareHouse: ' add Product To Ware House ',
        pleaseAddSellingPrice: ' please Add Selling Price ',
        buyingDate: ' buying Date ',
        sell: ' sells ',
        productCount: ' product Count ',
        totalInitialProfit: ' total Initial Profit ',
        totalProductPrice: ' total Product Price ',
        wareHouse: ' ware House ',
        totalSellingPrice: ' total Selling Price ',
        totalBuyingPrice: ' total Buying Price ',
        notEnoughProductToSell: ' not Enough Product To Sell ',
        quantityInWareHouse: ' quantity In Ware House ',
        wareHouseId: ' ware House Id ',
        sales: ' sales ',
        products: ' products ',
        typeId: ' typeId ',
        companyId: ' companyId ',
        saleId: ' sale Id ',
    },
    turkish: {
        name: ' isim ',
        company: ' şirket ',
        type: ' tür ',
        buyingPrice: ' alış fıyat ',
        sellingPrice: ' satış fıya ',
        date: ' tarih ',
        id: ' Id ',
        customer: ' müşteri ',
        productName: ' ürün adı ',
        productId: ' ürün no ',
        profit: ' kar ',
        quantity: ' miktar ',
        add: ' ekle ',
        totalSales: ' satış toplam ',
        soldProductsNumbers: ' satılan ürün sayısı ',
        totalProfit: ' toplama kar ',
        addToSoldProductList: ' satılan ürünlere elke ',
        pleaseInsertProductName: ' lütfan ürün adı ekleyin ',
        customerName: ' müşteri adı ',
        pleaseAddBuyingPrice: ' lütfan alınan ürün fıyatı ekleyin ',
        pleaseAddQuentity: ' lütfan mikar ekleyin ',
        addProduct: ' ürün ekle ',
        addProductToWareHouse: ' depoya ürün ekle ',
        pleaseAddSellingPrice: ' lütfen satış fiyatını ekleyin ',
        buyingDate: ' satın alma tarihi ',
        sell: ' sat ',
        sales: ' satış ',
        productCount: ' ürünlerin sayısı ',
        totalInitialProfit: ' toplam başlangıç karı ',
        totalProductPrice: ' toplam ürün fiyatı ',
        wareHouse: ' depo ',
        totalSellingPrice: ' toplam Satış Fiyatı ',
        totalBuyingPrice: ' toplam Alış Fiyatı ',
        notEnoughProductToSell: ' Yeterli Ürün Yok ',
        quantityInWareHouse: ' Depodaki miktar ',
        wareHouseId: ' depoda Id ',
        ürünler: ' ürünler ',
        typeId: ' tür Id ',
        companyId: ' şirken Id ',
        saleId: ' satış Id ',
    },
};
export default dectionary;
